version: "3"

services:
  innoscripta_allnewsy_api:
    build:
      context: ./innoscripta-news-backend
      dockerfile: Dockerfile
    container_name: innoscripta-allnewsy-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./innoscripta-news-backend:/var/www/html
    environment:
      APP_NAME: AllNewsy
      APP_ENV: production
      APP_DEBUG: 'true'
      PORT: 8080
      DB_CONNECTION: mysql
      DB_HOST: allnewsy_mysql_db
      DB_PORT: 3306
      DB_DATABASE: innoscripta-allnewsy
      DB_USERNAME: innoscripta_user
      DB_PASSWORD: changeme
      NEWS_API_BASE_URL: "https://newsapi.org/v2"
      NEWS_API_API_KEY: e4aefd4f085645f595bd58170d57d538
      THE_GUARDIAN_BASE_URL: "https://content.guardianapis.com"
      THE_GUARDIAN_API_KEY: 799a2c8e-2b6d-40aa-98c7-8a4cd997c777
      NYTIMES_BASE_URL: "https://api.nytimes.com/svc/search/v2"
      NYTIMES_API_KEY: LynuxtLoUx6QKD4fZLY6bW9rMGYvxyZ2
      
    depends_on:
      - allnewsy_mysql_db
    ports:
      - 8080:8080
    networks:
      - allnewsy-network
    entrypoint: ['sh', '/var/www/html/docker/entrypoint.sh']

  allnewsy_mysql_db:
    image: mysql:8.0
    container_name: allnewsy-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: innoscripta-allnewsy
      MYSQL_USER: innoscripta_user
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - allnewsy-network

  innoscripta-allnewsy-frontend:
    build:
      context: ./innoscripta-news-frontend
      dockerfile: Dockerfile
    container_name: react-app
    restart: unless-stopped
    volumes:
      - ./innoscripta-allnewsy-frontend:/usr/innoscripta-allnewsy-frontend
      - /usr/innoscripta-allnewsy-frontend/node_modules
    environment:
      - REACT_APP_BASE_URL=http://localhost:8080
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - allnewsy-network
    depends_on:
      - innoscripta_allnewsy_api

networks:
  allnewsy-network:
    driver: bridge

volumes:
  app: 
    driver: local